@startuml Cities
skinparam actorStyle awesome
left to right direction
actor "User" as u
package Cities {
  usecase "Request to API" as UC1
  usecase UC2 as "
  Choose a location
  ==
  Process values"
  usecase UC3 as "
  Request to GeoDBCities"
  usecase UC4 as "
  Request to NearBySearch"
  usecase UC5 as "
  Insert history"
  usecase "Response from API" as UC6
}

u --> UC1
UC1 -> UC2
UC2 -> UC3
UC3 -> UC4
UC4 -> UC5
UC5 -> UC6
u <-- UC6
@enduml