@startuml
left to right direction
actor "User" as u
rectangle Cities {
  usecase "Request to API" as UC1
  usecase "Pay for Food" as UC2
  usecase "Drink" as UC3
}
u --> UC1
u --> UC2
u --> UC3
@enduml