const RECOMMEND_FREQUENCY = Object.freeze({
  NONE: 0,
  MIDDLE: 1,
  HIGH: 2
})

const CURRENT_LOCATION_SUGGEST = Object.freeze({
  BROWSER: 0,
  PERMISSION: 1,
  UNAVAILABLE: 2,
  TIMEOUT: 3,
  SUGGEST: 4
})

export default {
  RECOMMEND_FREQUENCY,
  CURRENT_LOCATION_SUGGEST
}