name: trander-deploy-to-cloud-run
on:
  push:
    branches:
      - master
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      # Decode and put .env file
      # https://casualdevelopers.com/tech-tips/how-to-use-dotenv-with-base64-on-circleci/
      - name: Decode .env file
        run: |
          echo ${{ secrets.ENV_FILE }} | base64 --decode > src/.env

      # Configure Docker with Credentials
      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          docker build -f docker/php/Dockerfile.production -t us.gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} .

      # Push the Docker image
      - name: Push
        run: |
          docker push us.gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          gcloud run deploy ${{ secrets.GCP_APPLICATION }} \
          --image us.gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} \
          --region us-central1 \
          --platform=managed \
          --add-cloudsql-instances ${{ secrets.SQL_CONNECTION_NAME }} \
          --allow-unauthenticated
